springserver:
    #image:                   <-- spesifiserer lokalt bilde(allerede bygget)
    build: ./springserver                  # Bygger bilde p책 Dockerfile
    ports:
      - "8080:8080"                        #context: springserver   # Hvilken mappe Dockerfilen befinner seg
                              #dockerfile: Dockerfile  # Angir navnet p책 dockerfilen
    #ports:                    # - <port utenfor container>:<applikasjonens port inne i containeren>
    #  - "8080:8080"

documentationviewer:
    build: ./documentation-viewer                            # Bygger bilde p책 Dockerfile
    links:
          - springserver:springserver
    ports:                                     #context: documentation-viewer   # Mappen Dockerfilen befinner seg i
      - "80:3000"                                  #dockerfile: Dockerfile          # Navnet p책 dockerfilen
                                # - <port utenfor container>:<applikasjonens port inne i containeren>



