---
- hosts: all
  become: true
  tasks:

   - name: autoriser med gcloud private-key
     shell: gcloud auth activate-service-account --key-file /home/ubuntu/DevOpsEksamen-fd8bbc5d8acd.json

   - name: set default configurations
     shell: gcloud config set project devopseksamen
     shell: gcloud config set compute/zone europe-west3-a

   - name: push docker images to container registry
     shell: gcloud docker -- push eu.gcr.io/devopseksamen/springserver:v3
     become: true

   - name: choose existing cluster and get credentials
     shell: gcloud container clusters get-credentials dev-ops-cluster --zone europe-west3-a --project devopseksamen
#
#   - name: Run image on cluster
#     shell: kubectl run springserver --image=gcr.io/devopseksamen/springserver:v3 --port 8080

   - name: update already running app
     shell: kubectl set image deployment/springserver springserver=eu.gcr.io/devopseksamen/springserver:v3
     #shell: kubectl expose deployment springserver --type=LoadBalancer --port 80 --target-port 8080
