---
- hosts:
  tasks:

# environment variables set

# $DEV_OPS_DATACENTER
# $DEV_OPS_PROJECT_ID
# $DEV_OPS_CLUSTER_NAME

# LATEST_DOCKER_IMAGE="docker ps -n 2"



   - name: log in
     shell: gcloud init

   - name: autoriser med gcloud private-key
     shell: gcloud auth activate-service-account --key-file [KEY_FILE]

   - name: choose existing cluster and start proxy
     shell: gcloud container clusters get-credentials $DEV_OPS_CLUSTER_NAME --zone $DEV_OPS_DATACENTER --project $DEV_OPS_PROJECT_ID
     shell: kubectl proxy

   - name: run new app on cluster
     shell: kubectl run springserver --image=springserver --port 8080
     shell: kubectl run documentationviewer --image=documentationviewer --port 80

   - name: expose app by port on internet
     shell: kubectl expose deployment documentationviewer --type=LoadBalancer --port 80 --target-port 80

