---
- hosts: jenkins
  become: true

  environment:
    CLOUD_SDK_REPO: "cloud-sdk-$(lsb_release -c -s)"

  tasks:

   - name: Make apt use https
     apt:
       name: apt-transport-https
       state: present

   - name: install unzip
     apt:
       name: unzip
       state: present

   - name: Extract envconsul executable to path
     unarchive:
       src: https://releases.hashicorp.com/envconsul/0.6.2/envconsul_0.6.2_linux_amd64.tgz
       dest: /usr/local/bin
       remote_src: yes

   - name: change permissions on envconsul
     file: dest=/usr/local/bin mode=a+x

   - name: Install pip
     apt:
       name: python-pip
       state: present

   - name: Install docker
     apt:
       name: docker-ce
       state: present

   - name: Install docker-compose
     pip:
       name: docker-compose
       state: present


#   - name: start consul
#     shell: consul agent -dev
#     when:
#      - service: name=consul pattern=consul

#   - name: export gcloud environment variable
#     apt: name=CLOUD_SDK_REPO state=installed
#     environment: cloud-sdk-$(lsb_release -c -s)

   - name: add gcloud to repo
     apt_repository:
       repo: deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main
       state: present
       update_cache: yes


   - name: add gcloud public key to apt
     authorized_key:
       user: ubuntu
       state: present
       key: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       validate_certs: True

   - name: Install gcloud-cli
     apt:
       name: google-cloud-sdk
       state: present

   - name: Install kubectl
     apt:
       name: kubectl
       state: present


   - name: Remove dependencies that are no longer required
     apt:
       autoremove: yes
       name: "*"
       state: latest
       update_cache: yes
